#!/usr/bin/env bash

bindir=
libdir=
ref=

case "${1}" in
  init)
    while (( "$#" )); do
      case "${2}" in
        --blueprint=*) blueprint=${2/--blueprint=/''} ; shift ;;
        --password=*) password=${2/--password=/''} ; shift ;;
        --token=*) token=${2/--token=/''} ; shift ;;
        -b*) blueprint=${3} ; shift ; shift ;;
        -p*) password=${3} ; shift ; shift ;;
        -t*) token=${3} ; shift ; shift ;;
        *) test -n "${2}" && blueprint=${2} ; shift ;;
      esac
    done

    test -z "${blueprint}" && read -p 'Enter blueprint (e.g. ce_ops): ' blueprint
    test -z "${password}" && read -p 'Enter password: ' -s password && echo
    test -z "${token}" && read -p 'Enter GitHub access token: ' -s token && echo

    echo -n 'Downloading: '
    rm -f "${libdir}/.hykes-blueprints.tar.gz" && \
    curl --fail --silent --location --retry 4 --retry-delay 8 \
      --header "Authorization: token ${token}" \
      --header "Accept: application/vnd.github.v3.raw" \
      --output "${libdir}/.hykes-blueprints.tar.gz" \
      "https://api.github.com/repos/cloud-elements/hykes-blueprints/tarball/${ref}"
    case "$?" in
      0) echo 'done' ;;
      *) echo 'fail' ; exit 1 ;;
    esac

    echo -n 'Decompressing: '
    rm -rf "${libdir}/.hykes-blueprints" && \
    mkdir "${libdir}/.hykes-blueprints" && \
    tar -x -f "${libdir}/.hykes-blueprints.tar.gz" -C "${libdir}/.hykes-blueprints" --strip 1
    case "$?" in
      0) echo 'done' ;;
      *) echo 'fail' ; exit 1 ;;
    esac

    echo -n 'Building: '
    (cd "${libdir}/.hykes-blueprints" ; make install)
    case "$?" in
      0) echo 'done' ;;
      *) echo 'fail' ; exit 1 ;;
    esac

    echo -n 'Decrypting: '
    (cd "${libdir}/.hykes-blueprints" ; build/bin/hykes-blueprints decrypt "${blueprint}" --password="${password}" 2>&1 > /dev/null)
    case "$?" in
      0) echo 'done' ;;
      *) echo 'fail' ; exit 1 ;;
    esac

    echo -n 'Moving: '
    rm -f "${libdir}/cloud" && \
    mv "${libdir}/.hykes-blueprints/build/lib/${blueprint}/hykes.ini" "${libdir}/hykes.ini"
    case "$?" in
      0) echo 'done' ;;
      *) echo 'fail' ; exit 1 ;;
    esac
  ;;

  --help|-h)
    a=(${0//\// })
    bin=${a[${#a[@]}-1]}

    echo 'Usage:'
    echo "  ${bin} create <provider> [--combined|-c] [--local-dns|-l]"
    echo "  ${bin} init <blueprint> [--password|-p <password>] [--token|-t <token>]]"
    echo "  ${bin} destroy <provider> [--combined|-c] [--local-dns|-l]"
    echo
    echo "Setup Commands:"
    echo "  init    Initialize to use a specific blueprint"
    echo
    echo "Core Commands:"
    echo "  create     Create cloud"
    echo "  destroy    Destroy cloud"
  ;;

  --version|-v) echo 'v0.0.0' ;;

  *) ${0} --help ; exit 1 ;;
esac
