#!/usr/bin/env bash

cmd="${1}" ; shift

## Global utility functions #######################################################################
function pprint() {
  local blue='\033[1;34m'
  local green='\033[1;32m'
  local red='\033[1;31m'
  local normal='\033[0m'
  local white='\033[1;37m'

  while (( "$#" )); do
    case "${1}" in
      -n) local n='-n' ; shift ;;
      -q) local q='-q' ; shift ;;
      *)
        test -n "${1}" && test -n "${adj}" && local msg=${1}
        test -n "${1}" && test -z "${adj}" && local adj=${1}
        shift
      ;;
    esac
  done

  if [ -z "${q}" ]; then
    case "${adj}" in
      bad) echo -e ${n} "${red}${msg}${normal}" ;;
      good) echo -e ${n} "${green}${msg}${normal}" ;;
      head) echo -e ${n} "${blue}==>${normal} ${white}${msg}${normal}" ;;
      subhead) echo -e ${n} "${green}==>${normal} ${white}${msg}${normal}" ;;
      *) echo ${n} "${msg}" ;;
    esac
  fi
}
export -f pprint

## Argument and option parsing ####################################################################
while (( "$#" )); do
  case "${1}" in
    --cloud-provider=*) cloud=${1/--cloud-provider=/''} ; shift ;;
    --consolidated) consolidated=0 ; shift ;;
    --dns-provider=*) dns=${1/--dns-provider=/''} ; shift ;;
    --quiet) quiet='-q' ; shift ;;
    --specs=*) specs=${1/--specs=/''} ; shift ;;
    -C*) cloud=${2} ; shift ; shift ;;
    -D*) dns=${2} ; shift ; shift ;;
    -c) consolidated=0 ; shift ;;
    -q) quiet='-q' ; shift ;;
    -s*) specs=${2} ; shift ; shift ;;
    *)
      case "${cmd}" in
        provision|unprovision)
          test -n "${1}" && test -n "${cloud}" && dns=${1}
          test -n "${1}" && test -z "${cloud}" && cloud=${1}
        ;;
      esac
      shift
    ;;
  esac
done

## Argument and option prompting ##################################################################
case "${cmd}" in
  provision|unprovision)
    test -z "${cloud}" && read -e -p 'Enter cloud provider (e.g. aws, do): ' cloud
    test -z "${dns}" && read -e -p 'Enter DNS provider (e.g. aws, do, hosts): ' dns
  ;;
esac

## Argument and option defaults ###################################################################
test -z "${specs}" && specs='medium'

## Command utility functions ######################################################################
function list_inventory_servers() {
  echo "$(hykes-blueprint ls "${1}" --quiet)"
}
export -f list_inventory_servers

function lookup_inventory_fqdn() {
  local h=$(list_inventory_servers | head -n 1)
  echo "${h/app0./}"
}
export -f lookup_inventory_fqdn

# Cloud providers:
function await_do_server() {
  case "${2}" in
    active|inactive) tugboat wait "${1}" --state="${2}" ;;
    *)
      tugboat info "${1}" > /dev/null 2>&1
      case "$?" in
        0) sleep 10 ; await_do_server "${1}" "${2}" ;;
        *) return 0 ;;
      esac
    ;;
  esac
}
export -f await_do_server

function create_do_server() {
  tugboat create "${1}" --size="${2}"
}
export -f create_do_server

function destroy_do_server() {
  yes | tugboat destroy "${1}"
}
export -f destroy_do_server

function exists_do_server() {
  tugboat info "${1}" > /dev/null 2>&1
}
export -f exists_do_server

function lookup_do_server_ip() {
  echo "$(tugboat info -n "${1}" --attribute=ip4 --porcelain)"
}
export -f lookup_do_server_ip

function size_do_server() {
  case "${1}" in
    consolidated)
      local xsmall='512mb'
      local small='4gb'
      local medium='8gb'
      local large='16gb'
      local xlarge='64gb'

      echo "${!2}"
    ;;
    *) return 1 ;;
  esac
}
export -f size_do_server

function create_do_cloud() {
  local size=$(size_do_server consolidated "${specs}")
  echo "${1}" | xargs -I{} bash -c "create_do_server {} ${size}"
  echo "${1}" | xargs -I{} bash -c "await_do_server {} active"
}
export -f create_do_cloud

function destroy_do_cloud() {
  echo "${1}" | xargs -I{} bash -c "destroy_do_server {}"
  echo "${1}" | xargs -I{} bash -c "await_do_server {} destroyed"
}
export -f destroy_do_cloud

function exists_do_cloud() {
  echo "${1}" | xargs -I{} bash -c '! exists_do_server {}'
  case "$?" in
    0) return 1 ;;
    *) return 0 ;;
  esac
}
export -f exists_do_cloud

# DNS providers:
function create_hosts_map() {
  echo "${1} ${2}" | sudo tee -a /etc/hosts
}
export -f create_hosts_map

function destroy_hosts_map() {
  sudo sed -i '' "/^${1}/d" /etc/hosts
}
export -f destroy_hosts_map

function create_hosts_maps_consolidated() {
  local fqdn=$(lookup_inventory_fqdn)
  local all=$(list_inventory_servers)
  local app=$(list_inventory_servers 'app')
  local appcount=$(echo "${app}" | wc -l | tr ' ' '\0')

  # Loop through all consolidated servers, determine their IP, and then create map in /etc/hosts.
  # The primary loadbalance role, which exists on the first consolidated server, needs to have
  # "extra" records so that the core endpoints are reachable upon the cloud being successfully
  # built (e.g. api.example.com, console.example.com)
  for ((i=0; i<=appcount-1; i++)); do
    local a=$(echo "${app}" | sed -n "$(( ${i} + 1 ))p")
    local ip=$(lookup_do_server_ip "${a}")
    local rs=$(echo "${all}" | grep "${i}." | tr '\n' ' ')
    if [ ${i} -eq 0 ]; then
      rs="${rs}${fqdn} api.${fqdn} console.${fqdn} logs.${fqdn}"
    fi

    create_hosts_map "${ip}" "${rs}"
  done
}
export -f create_hosts_maps_consolidated

function destroy_hosts_maps() {
  local srvcount=$(echo "${1}" | wc -l | tr ' ' '\0')

  for ((i=0; i<=srvcount-1; i++)); do
    local a=$(echo "${1}" | sed -n "$(( ${i} + 1 ))p")
    local ip=$(lookup_do_server_ip "${a}")

    destroy_hosts_map "${ip}"
  done
}
export -f destroy_hosts_maps

## Command functions ##############################################################################
function help() {
  a=(${0//\// })
  bin=${a[${#a[@]}-1]}

  echo 'Usage:'
  echo "  ${bin} provision <cloud-provider> <dns-provider>"
  echo '    [--consolidated|-c] [--specs|-s <xsmall|small|medium|large|xlarge>] [--quiet|-q]'
  echo "  ${bin} unprovision <cloud-provider> <dns-provider>"
  echo '    [--consolidated|-c] [--quiet|-q]'
  echo
  echo 'Core Commands:'
  echo '  provision      Provision cloud'
  echo '  unprovision    Unprovision cloud'
  echo
  echo 'More Information:'
  echo '  docs     https://developers.cloud-elements.com'
  echo '  forum    https://forum.cloud-elements.com'
  echo '  repo     https://github.com/cloud-elements/hykes-provision'
}

function provision() {
  pprint head 'Provisioning' ${quiet}

  case "${cloud}" in
    do)
      case "${consolidated}" in
        0)
          local app=$(list_inventory_servers 'app')

          pprint subhead 'Checking for existing cloud' ${quiet}
          ! exists_do_cloud "${app}" || \
            { pprint bad 'failed (cloud should not exist)' ${quiet} ; return 1; }

          pprint subhead 'Creating cloud' ${quiet}
          create_do_cloud "${app}" || { pprint bad 'failed' ${quiet} ; return 1; }

          case "${dns}" in
            hosts)
              pprint subhead 'Creating DNS' ${quiet}
              create_hosts_maps_consolidated || { pprint bad 'failed' ${quiet} ; return 1; }
            ;;
          esac
        ;;
      esac
    ;;
  esac
}

function unprovision() {
  pprint head 'Unprovisioning' ${quiet}

  case "${cloud}" in
    do)
      case "${consolidated}" in
        0)
          local app=$(list_inventory_servers 'app')

          pprint subhead 'Checking for existing cloud' ${quiet}
          exists_do_cloud "${app}" || \
            { pprint bad 'failed (cloud should exist)' ${quiet} ; return 1; }

          case "${dns}" in
            hosts)
              pprint subhead 'Destroying DNS' ${quiet}
              destroy_hosts_maps "${app}" || { pprint bad 'failed' ${quiet} ; return 1; }
            ;;
          esac

          pprint subhead 'Destroying cloud' ${quiet}
          destroy_do_cloud "${app}" || { pprint bad 'failed' ${quiet} ; return 1; }
        ;;
      esac
    ;;
  esac
}

function version() {
  echo 'v0.1.0'
}

## Command routing ################################################################################
case "${cmd}" in
  --help|-h) help ; exit 0 ;;
  --version|-v) version ; exit 0 ;;
  provision|unprovision) "${cmd}" ; exit "$?" ;;
  *) help ; exit 1 ;;
esac
